/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CyberSafetyRouteImport } from './routes/cyber-safety'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HealthRouteImport } from './routes/health'
import { Route as StudentRouteImport } from './routes/student'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSafetyRoute = CyberSafetyRouteImport.update({
  id: '/cyber-safety',
  path: '/cyber-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cyber-safety' | '/documents' | '/health' | '/student' | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/cyber-safety' | '/documents' | '/health' | '/student' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/cyber-safety'
    | '/documents'
    | '/health'
    | '/student'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyberSafetyRoute: typeof CyberSafetyRoute
  DocumentsRoute: typeof DocumentsRoute
  HealthRoute: typeof HealthRoute
  StudentRoute: typeof StudentRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-safety': {
      id: '/cyber-safety'
      path: '/cyber-safety'
      fullPath: '/cyber-safety'
      preLoaderRoute: typeof CyberSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyberSafetyRoute: CyberSafetyRoute,
  DocumentsRoute: DocumentsRoute,
  HealthRoute: HealthRoute,
  StudentRoute: StudentRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
