/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CyberSafetyRouteImport } from './routes/cyber-safety'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProjectLabRouteImport } from './routes/project-lab'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StudentRouteImport } from './routes/student'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnModuleIdRouteImport } from './routes/learn.$moduleId'
import { Route as LearnPythonRouteImport } from './routes/learn.python'
import { Route as LearnPythonIndexRouteImport } from './routes/learn.python.index'
import { Route as LearnPythonModuleIdRouteImport } from './routes/learn.python.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSafetyRoute = CyberSafetyRouteImport.update({
  id: '/cyber-safety',
  path: '/cyber-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectLabRoute = ProjectLabRouteImport.update({
  id: '/project-lab',
  path: '/project-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnModuleIdRoute = LearnModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPythonRoute = LearnPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPythonIndexRoute = LearnPythonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnPythonRoute,
} as any)
const LearnPythonModuleIdRoute = LearnPythonModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearnPythonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRouteWithChildren
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/project-lab': typeof ProjectLabRoute
  '/roadmap': typeof RoadmapRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/python': typeof LearnPythonRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/python/$moduleId': typeof LearnPythonModuleIdRoute
  '/learn/python/': typeof LearnPythonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/project-lab': typeof ProjectLabRoute
  '/roadmap': typeof RoadmapRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn': typeof LearnIndexRoute
  '/learn/python/$moduleId': typeof LearnPythonModuleIdRoute
  '/learn/python': typeof LearnPythonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cyber-safety': typeof CyberSafetyRoute
  '/documents': typeof DocumentsRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRouteWithChildren
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/project-lab': typeof ProjectLabRoute
  '/roadmap': typeof RoadmapRoute
  '/student': typeof StudentRoute
  '/workspace': typeof WorkspaceRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/python': typeof LearnPythonRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/python/$moduleId': typeof LearnPythonModuleIdRoute
  '/learn/python/': typeof LearnPythonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/cyber-safety'
    | '/documents'
    | '/health'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/project-lab'
    | '/roadmap'
    | '/student'
    | '/workspace'
    | '/learn/$moduleId'
    | '/learn/python'
    | '/learn/'
    | '/learn/python/$moduleId'
    | '/learn/python/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/cyber-safety'
    | '/documents'
    | '/health'
    | '/practice'
    | '/progress'
    | '/project-lab'
    | '/roadmap'
    | '/student'
    | '/workspace'
    | '/learn/$moduleId'
    | '/learn'
    | '/learn/python/$moduleId'
    | '/learn/python'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/chat'
    | '/cyber-safety'
    | '/documents'
    | '/health'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/project-lab'
    | '/roadmap'
    | '/student'
    | '/workspace'
    | '/learn/$moduleId'
    | '/learn/python'
    | '/learn/'
    | '/learn/python/$moduleId'
    | '/learn/python/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CyberSafetyRoute: typeof CyberSafetyRoute
  DocumentsRoute: typeof DocumentsRoute
  HealthRoute: typeof HealthRoute
  LearnRoute: typeof LearnRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ProjectLabRoute: typeof ProjectLabRoute
  RoadmapRoute: typeof RoadmapRoute
  StudentRoute: typeof StudentRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-safety': {
      id: '/cyber-safety'
      path: '/cyber-safety'
      fullPath: '/cyber-safety'
      preLoaderRoute: typeof CyberSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-lab': {
      id: '/project-lab'
      path: '/project-lab'
      fullPath: '/project-lab'
      preLoaderRoute: typeof ProjectLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$moduleId': {
      id: '/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof LearnModuleIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/python': {
      id: '/learn/python'
      path: '/python'
      fullPath: '/learn/python'
      preLoaderRoute: typeof LearnPythonRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/python/': {
      id: '/learn/python/'
      path: '/'
      fullPath: '/learn/python/'
      preLoaderRoute: typeof LearnPythonIndexRouteImport
      parentRoute: typeof LearnPythonRoute
    }
    '/learn/python/$moduleId': {
      id: '/learn/python/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/python/$moduleId'
      preLoaderRoute: typeof LearnPythonModuleIdRouteImport
      parentRoute: typeof LearnPythonRoute
    }
  }
}

interface LearnPythonRouteChildren {
  LearnPythonModuleIdRoute: typeof LearnPythonModuleIdRoute
  LearnPythonIndexRoute: typeof LearnPythonIndexRoute
}

const LearnPythonRouteChildren: LearnPythonRouteChildren = {
  LearnPythonModuleIdRoute: LearnPythonModuleIdRoute,
  LearnPythonIndexRoute: LearnPythonIndexRoute,
}

const LearnPythonRouteWithChildren = LearnPythonRoute._addFileChildren(
  LearnPythonRouteChildren,
)

interface LearnRouteChildren {
  LearnModuleIdRoute: typeof LearnModuleIdRoute
  LearnPythonRoute: typeof LearnPythonRouteWithChildren
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnModuleIdRoute: LearnModuleIdRoute,
  LearnPythonRoute: LearnPythonRouteWithChildren,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CyberSafetyRoute: CyberSafetyRoute,
  DocumentsRoute: DocumentsRoute,
  HealthRoute: HealthRoute,
  LearnRoute: LearnRouteWithChildren,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ProjectLabRoute: ProjectLabRoute,
  RoadmapRoute: RoadmapRoute,
  StudentRoute: StudentRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
